### ISSUE TITLE
Correct error message

### ISSUE THREAD

**Issue by ThomasArts** [helium/blockchain-core#872]
I bumped into the error message `duplicate_group` when creating an election transaction on the wrong height. I wonder if this error message name is intentional or happened to get there by accident.

https://github.com/helium/blockchain-core/blob/336ce44bab40a4535571a9071a55b3a0add65de0/src/transactions/v1/blockchain_txn_consensus_group_v1.erl#L147

**Comment by vihu** [comment]
I suppose the error could be worded better but essentially it's saying that an election has already occurred at the `BaseHeight` and the new proposal is "duplicate". For example:

```
(blockchain_etl@127.0.0.1)1> {blockchain_ledger_v1:current_height(blockchain:ledger()), blockchain_ledger_v1:election_height(blockchain:ledger())}.
{{ok,890375},{ok,890333}}
```
So, `BaseHeight=890333` in this example, any subsequent consensus_group txn submissions would fail because the network already had an election occur.

Also noteworthy is that consensus group transactions cannot be submitted by users by design, because of obvious security concerns (everyone would start proposing their own Hotspots in the consensus group, all the time).
